version: '3.5'

services:
  postgres:
    image: postgres:12-alpine
    env_file:
       - postgres.env
    volumes:
      - postgres:/data/postgres
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-leader
 
  server:
    image: airflow2-docker:1.0.0
    env_file:
       - airflow.env
       - airflow_db.env
    ports:
      - "8080:8080"
    volumes:
       - ./dags:/opt/airflow/dags
       - /var/run/docker.sock:/var/run/docker.sock:rw # Docker socket
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-leader

volumes:
    postgres:

networks:
 default:
   driver: overlay
   driver_opts:
     com.docker.network.driver.mtu: 1400